print("Career Skills for IT Companies,credit:1")
print("Communication Skills for Global Professionals,credit:1")
print("High Performance Computing,credit:4")
print("Undergraduate Research in Computer Science,credit:3")
print("Seminar on Special Topics in Emerging Areas,credit:2")
print("Capstone Design,credit:1")
print("Advanced Database Management System,credit:3")
print("Devops Engineering Practice,credit:3")
print("Environment and Sustainability,credit:2")
print("mehul tyagi e19cse085")
